### ISSUE TITLE
Problem with the tooltip generator when there are comments in the abilities file

### ISSUE THREAD

**Issue by Zavian** [Myll/Dota-2-ModKit#16]
As title, when you try to generate tooltips in an npc_abilities_custom with comments (valve style) it won't simply find abilities.
Example: 
![screenshot_1](https://cloud.githubusercontent.com/assets/6689716/5944919/0de33c7e-a72b-11e4-95da-6e4e9655d6f7.png)

**Comment by Myll** [comment]
Hi, are you sure the ability hasn’t already been defined in addon_english? D2ModKit won’t make tooltips for entries it detects in addon_language files.

**Comment by Zavian** [comment]
Of course.
I tried to delete all the comments in the file and the tooltip generetor works fine, but when I reinsert my comments it just ignore everything.
Here you can see the "inciminated" file. https://github.com/Zavian/dota_werewolf/blob/master/scripts/npc/npc_abilities_custom.txt

**Comment by Myll** [comment]
Alright, thanks. I’ll take a look at it when I get home.
