### ISSUE TITLE
Weave particle issue

### ISSUE THREAD

**Issue by Pizzalol** [Myll/Dota-2-ModKit#31]
I'm not sure if this is an actual issue as it might be me failing to understand how it works

I selected all the dazzle Weave particle files and then I try to resize, rename and recolor them but that leads to the particle being a flickering ray for 1-2 seconds in the game

Renaming and recoloring the particle works flawlessly and ingame it shows up properly but its too big for me so I need to shrink it and as soon as I try to do any resizing it messes up the particle

**Comment by Pizzalol** [comment]
Fixed it by manually editing the size

**Comment by Myll** [comment]
When I wrote particle re-sizing, I guess I wasn't thinking properly, haha. Shrinking should only go to a minimum of -100%, not -200%.

Also, gfy demo: http://gfycat.com/IdioticMarvelousBee
