### ISSUE TITLE
D2ModKit v1.4.8.2 crashes with CLR20r3

### ISSUE THREAD

**Issue by minecraft2048** [Myll/Dota-2-ModKit#36]
D2ModKit is at C:\Users\USER\Documents\Dota 2 Development, Dota 2 is at C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta

Decompiled particles has been installed, and when I try to launch the application, it immediately crashes with this:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	d2modkit.exe
  Problem Signature 02:	1.4.8.2
  Problem Signature 03:	550db666
  Problem Signature 04:	D2ModKit
  Problem Signature 05:	1.4.8.2
  Problem Signature 06:	550db666
  Problem Signature 07:	fb
  Problem Signature 08:	102
  Problem Signature 09:	System.TypeInitialization
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by Myll** [comment]
This seems like a problem related to D2ModKit trying to access the registry, according to [this](http://www.personalcomputerfixes.com/general-errors/how-to-fix-clr20r3-error/). ModKit accesses the registry to try and auto find your dota 2 installation path. I will have to remove the registry access and then have you try it out.

**Comment by Myll** [comment]
[Try this version](https://mega.co.nz/#!kwgH1SzI!UUWeqc-plpgsERWWDpSdx9co_zo6x9D92c3nAKqOzMQ)

**Comment by minecraft2048** [comment]
Downloaded it, then I remove every file and folder in Dota 2 Development, then I extract the new one with decompiled particles, and same error happens

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	d2modkit.exe
  Problem Signature 02:	1.4.8.2
  Problem Signature 03:	5520aed2
  Problem Signature 04:	D2ModKit
  Problem Signature 05:	1.4.8.2
  Problem Signature 06:	5520aed2
  Problem Signature 07:	fb
  Problem Signature 08:	102
  Problem Signature 09:	System.TypeInitialization
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

Removing decompiled particle doesn't help

**Comment by Myll** [comment]
are you on windows XP? i don't think it will run that OS because you need .NET Framework v4.5.

**Comment by minecraft2048** [comment]
Installing .NET framework fixes the problem! I'm on Windows 7 btw. If only Microsoft provides better error like you need to install .Net v4.5 instead of weird CLR20r3 error that google doesn't return solutions for me...
