### ISSUE TITLE
Opening the program doesn't do anything

### ISSUE THREAD

**Issue by epitaque** [Myll/Dota-2-ModKit#37]
It turns the cursor to the loading symbol for a second and then doesn't do anything.
To reproduce, just download the zip file, extract it to a file, and run the exe. I'm running Windows 8.1 if that is helpful.

**Comment by Pizzalol** [comment]
did you put it in the same disk drive on which you installed dota?

**Comment by epitaque** [comment]
Nope, that would probably be the problem.
