### ISSUE TITLE
v1.4.8.4  |  Opens, shows up in processes, and closes.

### ISSUE THREAD

**Issue by CrAzD** [Myll/Dota-2-ModKit#40]
When I launch D2ModKit v1.4.8.4 nothing opens. It shows up in my processes for a few seconds and then closes. No errors, popups, nothing at all.

If I use an older version all that happens is it opens the latest releases page. 
It's in the same folder as Dota 2. 
I've tried all levels of the dota 2 directory, root and beyond. Nothing
Tried on my desktop nothing.
I only have 1 disk as well.
I've reinstalled microsoft.net framework 4.5.2
Latest version of visual c++ 2008, 10, 12, and 13 if that matters.

Any ideas as to what it could be?

**Comment by Myll** [comment]
Delete appdata/local/d2modkit

**Comment by CrAzD** [comment]
Didn't fix it. 

Once I delete appdata/local/d2modkit, it opens the latest releases webpage and remakes the folder. It also won't upon the webpage again until I delete the folder. I can repeat it all day long. However the app never shows up.

**Comment by Myll** [comment]
Sorry, I don't know. I can't be bothered to update modkit currently, as I have a popular mod that demands most of my attention now.

**Comment by Silent331** [comment]
Solved with

https://github.com/Myll/Dota-2-ModKit/issues/41

**Comment by Myll** [comment]
[New Reborn-compatible modkit released](https://github.com/Myll/Dota-2-ModKit/releases/tag/v1.4.8.5)
