### ISSUE TITLE
D2ModKit.exe wont run with reborn tools unless legacy folders exist

### ISSUE THREAD

**Issue by Silent331** [Myll/Dota-2-ModKit#41]
The client fails to run unless the following folders exist

SteamApps\common\dota 2 beta\dota_ugc\game\dota_addons\%defaultaddonname%

SteamApps\common\dota 2 beta\dota_ugc\content\dota_addons\%defaultaddonname%

Where the default addon name is listed in 

SteamApps\common\dota 2 beta\game\dota_addons\dota2cfg.cfg

"dota2cfg"
{
	"default"		"%defaultaddonname%"
}

**Comment by Myll** [comment]
Thanks for the clear explanation.

**Comment by NoFluxGiven** [comment]
Even after confirming the above, the application still refuses to run.

I have two folders:

Steam\SteamApps\common\dota 2 beta\dota_ugc\game\dota_addons\custom_dota_pvp
Steam\SteamApps\common\dota 2 beta\dota_ugc\content\dota_addons\custom_dota_pvp

With the following file:

"dota2cfg"
{
	"default"		"custom_dota_pvp"
}

**Comment by Myll** [comment]
[New Reborn-compatible modkit released](https://github.com/Myll/Dota-2-ModKit/releases/tag/v1.4.8.5)
